### ISSUE TITLE
Multibuilder can`t build the block

### ISSUE THREAD

**Issue by haiman233** [Bunnky/SensibleToolboxReborn#1]
According to lore, the following error appears.
[14:19:35 错误]: Could not pass event PlayerInteractEvent to SensibleToolbox v1.0.0
java.lang.NoSuchFieldError: Class org.bukkit.enchantments.Enchantment does not have member field 'org.bukkit.enchantments.Enchantment SHARPNESS'
	at io.github.thebusybiscuit.sensibletoolbox.items.multibuilder.MultiBuilder.handleExchangeMode(MultiBuilder.java:231) ~[SensibleToolbox.Reborn.v1.0.0.jar:?]
	at io.github.thebusybiscuit.sensibletoolbox.items.multibuilder.MultiBuilder.onInteractItem(MultiBuilder.java:179) ~[SensibleToolbox.Reborn.v1.0.0.jar:?]
	at io.github.thebusybiscuit.sensibletoolbox.listeners.GeneralListener.onPlayerInteract(GeneralListener.java:71) ~[SensibleToolbox.Reborn.v1.0.0.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor381.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-2018]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-2018]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-2018]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:566) ~[purpur-1.20.1.jar:git-Purpur-2018]
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:539) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:2043) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.1.jar:git-Purpur-2018]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1366) ~[purpur-1.20.1.jar:git-Purpur-2018]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.1.jar:git-Purpur-2018]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1343) ~[purpur-1.20.1.jar:git-Purpur-2018]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1336) ~[purpur-1.20.1.jar:git-Purpur-2018]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1314) ~[purpur-1.20.1.jar:git-Purpur-2018]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[purpur-1.20.1.jar:git-Purpur-2018]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2018]
	at java.lang.Thread.run(Thread.java:1570) ~[?:?]

**Comment by haiman233** [comment]
And it seems that Multibuilder can't charge in Electrical Energizer.

**Comment by Bunnky** [comment]
Thank you for the report!

 The Multibuilder is charged by right clicking with an energy cell, not the Electrical Energizer
 
 Enchantment compatibility fixed, new jar: https://github.com/Bunnky/SensibleToolboxReborn/releases/tag/1.0.1

**Comment by haiman233** [comment]
> Thank you for the report!
> 
> The Multibuilder is charged by right clicking with an energy cell, not the Electrical Energizer

OK，Thanks

**Comment by haiman233** [comment]
But there is also a funny bug :(
